import type {
  Announcement,
  Asset,
  AssetEvent,
  AttendanceCorrection,
  AttendanceRecord,
  AuditEntry,
  Candidate,
  Department,
  DocumentItem,
  Employee,
  ExpenseClaim,
  Goal,
  HeadcountPoint,
  HelpdeskTicket,
  JobOpening,
  LeaveRequest,
  NotificationItem,
  OnboardingJourney,
  PayrollRun,
  Payslip,
  PerformanceReview,
  Shift,
  TrendPoint,
} from "@/types";

/**
 * Demo fixtures only. Every service reads from here today and will read from
 * Supabase tomorrow — component code never imports this file directly.
 */

export const employees: Employee[] = [
  {
    id: "e1",
    code: "PF-1001",
    firstName: "Aarav",
    lastName: "Sharma",
    email: "aarav.sharma@jeevijay-hrms.example",
    phone: "+91 98200 11223",
    department: "Engineering",
    designation: "Engineering Manager",
    role: "team_lead",
    managerName: "Neha Kapoor",
    location: "Bengaluru",
    joinedOn: "2021-03-15",
    status: "active",
    employmentType: "full-time",
    shift: "General (09:30 - 18:30)",
    gender: "Male",
    dateOfBirth: "1990-07-12",
    bloodGroup: "O+",
    maritalStatus: "Married",
    address: "14 Indiranagar, Bengaluru, KA 560038",
    emergencyContact: { name: "Priya Sharma", relation: "Spouse", phone: "+91 98200 44556" },
    bank: {
      accountName: "Aarav Sharma",
      accountNumber: "XXXX XXXX 4412",
      ifsc: "HDFC0001234",
      bankName: "HDFC Bank",
    },
    ctcAnnual: 3600000,
    leaveBalance: { casual: 6, sick: 4, earned: 12, unpaid: 0 },
  },
  {
    id: "e2",
    code: "PF-1002",
    firstName: "Meera",
    lastName: "Iyer",
    email: "meera.iyer@jeevijay-hrms.example",
    phone: "+91 99001 23456",
    department: "Human Resources",
    designation: "HR Business Partner",
    role: "hr",
    managerName: "Neha Kapoor",
    location: "Pune",
    joinedOn: "2022-06-01",
    status: "active",
    employmentType: "full-time",
    shift: "General (09:30 - 18:30)",
    gender: "Female",
    dateOfBirth: "1993-01-24",
    bloodGroup: "B+",
    maritalStatus: "Single",
    address: "Baner Road, Pune, MH 411045",
    emergencyContact: { name: "Lata Iyer", relation: "Mother", phone: "+91 99001 77889" },
    bank: {
      accountName: "Meera Iyer",
      accountNumber: "XXXX XXXX 9081",
      ifsc: "ICIC0004521",
      bankName: "ICICI Bank",
    },
    ctcAnnual: 1800000,
    leaveBalance: { casual: 8, sick: 6, earned: 9, unpaid: 0 },
  },
  {
    id: "e3",
    code: "PF-1003",
    firstName: "Rohit",
    lastName: "Verma",
    email: "rohit.verma@jeevijay-hrms.example",
    phone: "+91 90909 33445",
    department: "Engineering",
    designation: "Senior Frontend Engineer",
    role: "employee",
    managerName: "Aarav Sharma",
    location: "Remote - Jaipur",
    joinedOn: "2023-02-20",
    status: "active",
    employmentType: "full-time",
    shift: "General (09:30 - 18:30)",
    gender: "Male",
    dateOfBirth: "1995-11-02",
    bloodGroup: "A+",
    maritalStatus: "Single",
    address: "Vaishali Nagar, Jaipur, RJ 302021",
    emergencyContact: { name: "Suresh Verma", relation: "Father", phone: "+91 90909 55667" },
    bank: {
      accountName: "Rohit Verma",
      accountNumber: "XXXX XXXX 7734",
      ifsc: "SBIN0007712",
      bankName: "State Bank of India",
    },
    ctcAnnual: 2200000,
    leaveBalance: { casual: 4, sick: 5, earned: 11, unpaid: 1 },
  },
  {
    id: "e4",
    code: "PF-1004",
    firstName: "Neha",
    lastName: "Kapoor",
    email: "neha.kapoor@jeevijay-hrms.example",
    phone: "+91 98111 66778",
    department: "Leadership",
    designation: "Chief People Officer",
    role: "admin",
    managerName: null,
    location: "Bengaluru",
    joinedOn: "2019-08-05",
    status: "active",
    employmentType: "full-time",
    shift: "General (09:30 - 18:30)",
    gender: "Female",
    dateOfBirth: "1986-04-18",
    bloodGroup: "AB+",
    maritalStatus: "Married",
    address: "Koramangala, Bengaluru, KA 560095",
    emergencyContact: { name: "Vikram Kapoor", relation: "Spouse", phone: "+91 98111 99001" },
    bank: {
      accountName: "Neha Kapoor",
      accountNumber: "XXXX XXXX 1120",
      ifsc: "AXIS0003311",
      bankName: "Axis Bank",
    },
    ctcAnnual: 5600000,
    leaveBalance: { casual: 9, sick: 7, earned: 18, unpaid: 0 },
  },
  {
    id: "e5",
    code: "PF-1005",
    firstName: "Sana",
    lastName: "Khan",
    email: "sana.khan@jeevijay-hrms.example",
    phone: "+91 97777 12121",
    department: "Design",
    designation: "Product Designer",
    role: "employee",
    managerName: "Aarav Sharma",
    location: "Hyderabad",
    joinedOn: "2024-01-08",
    status: "probation",
    employmentType: "full-time",
    shift: "Flexible (11:00 - 20:00)",
    gender: "Female",
    dateOfBirth: "1998-09-30",
    bloodGroup: "O-",
    maritalStatus: "Single",
    address: "Gachibowli, Hyderabad, TS 500032",
    emergencyContact: { name: "Imran Khan", relation: "Brother", phone: "+91 97777 34343" },
    bank: {
      accountName: "Sana Khan",
      accountNumber: "XXXX XXXX 5590",
      ifsc: "KKBK0005512",
      bankName: "Kotak Mahindra",
    },
    ctcAnnual: 1500000,
    leaveBalance: { casual: 3, sick: 3, earned: 2, unpaid: 0 },
  },
  {
    id: "e6",
    code: "PF-1006",
    firstName: "Daniel",
    lastName: "Fernandes",
    email: "daniel.f@jeevijay-hrms.example",
    phone: "+91 96666 54321",
    department: "Sales",
    designation: "Account Executive",
    role: "employee",
    managerName: "Priyanka Rao",
    location: "Mumbai",
    joinedOn: "2022-11-14",
    status: "notice",
    employmentType: "full-time",
    shift: "General (09:30 - 18:30)",
    gender: "Male",
    dateOfBirth: "1992-02-11",
    bloodGroup: "B-",
    maritalStatus: "Married",
    address: "Bandra West, Mumbai, MH 400050",
    emergencyContact: { name: "Maria Fernandes", relation: "Spouse", phone: "+91 96666 78787" },
    bank: {
      accountName: "Daniel Fernandes",
      accountNumber: "XXXX XXXX 3345",
      ifsc: "HDFC0009911",
      bankName: "HDFC Bank",
    },
    ctcAnnual: 1900000,
    leaveBalance: { casual: 2, sick: 1, earned: 6, unpaid: 2 },
  },
  {
    id: "e7",
    code: "PF-1007",
    firstName: "Priyanka",
    lastName: "Rao",
    email: "priyanka.rao@jeevijay-hrms.example",
    phone: "+91 95555 10101",
    department: "Sales",
    designation: "Regional Sales Manager",
    role: "team_lead",
    managerName: "Neha Kapoor",
    location: "Mumbai",
    joinedOn: "2020-05-18",
    status: "active",
    employmentType: "full-time",
    shift: "General (09:30 - 18:30)",
    gender: "Female",
    dateOfBirth: "1989-12-05",
    bloodGroup: "A-",
    maritalStatus: "Married",
    address: "Powai, Mumbai, MH 400076",
    emergencyContact: { name: "Sunil Rao", relation: "Spouse", phone: "+91 95555 20202" },
    bank: {
      accountName: "Priyanka Rao",
      accountNumber: "XXXX XXXX 8876",
      ifsc: "ICIC0008812",
      bankName: "ICICI Bank",
    },
    ctcAnnual: 3100000,
    leaveBalance: { casual: 7, sick: 5, earned: 14, unpaid: 0 },
  },
  {
    id: "e8",
    code: "PF-1008",
    firstName: "Karthik",
    lastName: "Nair",
    email: "karthik.nair@jeevijay-hrms.example",
    phone: "+91 94444 60606",
    department: "Finance",
    designation: "Payroll Analyst",
    role: "employee",
    managerName: "Neha Kapoor",
    location: "Kochi",
    joinedOn: "2023-09-11",
    status: "active",
    employmentType: "contract",
    shift: "General (09:30 - 18:30)",
    gender: "Male",
    dateOfBirth: "1994-06-22",
    bloodGroup: "O+",
    maritalStatus: "Single",
    address: "Kakkanad, Kochi, KL 682030",
    emergencyContact: { name: "Anita Nair", relation: "Mother", phone: "+91 94444 70707" },
    bank: {
      accountName: "Karthik Nair",
      accountNumber: "XXXX XXXX 2299",
      ifsc: "FDRL0001122",
      bankName: "Federal Bank",
    },
    ctcAnnual: 1400000,
    leaveBalance: { casual: 5, sick: 4, earned: 7, unpaid: 0 },
  },
];

export const departments: Department[] = [
  {
    id: "d1",
    name: "Engineering",
    head: "Aarav Sharma",
    headcount: 86,
    openRoles: 7,
    designations: ["Frontend Engineer", "Backend Engineer", "QA Engineer", "Engineering Manager"],
    costCenter: "CC-ENG-01",
  },
  {
    id: "d2",
    name: "Human Resources",
    head: "Meera Iyer",
    headcount: 12,
    openRoles: 1,
    designations: ["HR Executive", "HR Business Partner", "Talent Acquisition"],
    costCenter: "CC-HR-01",
  },
  {
    id: "d3",
    name: "Sales",
    head: "Priyanka Rao",
    headcount: 41,
    openRoles: 5,
    designations: ["SDR", "Account Executive", "Regional Sales Manager"],
    costCenter: "CC-SLS-01",
  },
  {
    id: "d4",
    name: "Design",
    head: "Sana Khan",
    headcount: 14,
    openRoles: 2,
    designations: ["Product Designer", "Design Lead", "UX Researcher"],
    costCenter: "CC-DSG-01",
  },
  {
    id: "d5",
    name: "Finance",
    head: "Karthik Nair",
    headcount: 18,
    openRoles: 1,
    designations: ["Payroll Analyst", "Accountant", "Finance Manager"],
    costCenter: "CC-FIN-01",
  },
  {
    id: "d6",
    name: "Leadership",
    head: "Neha Kapoor",
    headcount: 6,
    openRoles: 0,
    designations: ["Chief People Officer", "VP Engineering", "VP Sales"],
    costCenter: "CC-LDR-01",
  },
];

export const attendance: AttendanceRecord[] = [
  {
    id: "a1",
    employeeId: "e3",
    employeeName: "Rohit Verma",
    date: "2026-08-17",
    checkIn: "09:26",
    checkOut: "18:42",
    workedHours: 8.6,
    overtimeHours: 0.4,
    status: "wfh",
    shift: "General",
    source: "web",
  },
  {
    id: "a2",
    employeeId: "e1",
    employeeName: "Aarav Sharma",
    date: "2026-08-17",
    checkIn: "09:58",
    checkOut: "19:05",
    workedHours: 8.4,
    overtimeHours: 0.6,
    status: "late",
    shift: "General",
    source: "biometric",
  },
  {
    id: "a3",
    employeeId: "e5",
    employeeName: "Sana Khan",
    date: "2026-08-17",
    checkIn: "11:04",
    checkOut: "16:10",
    workedHours: 4.6,
    overtimeHours: 0,
    status: "half-day",
    shift: "Flexible",
    source: "mobile",
  },
  {
    id: "a4",
    employeeId: "e6",
    employeeName: "Daniel Fernandes",
    date: "2026-08-17",
    checkIn: null,
    checkOut: null,
    workedHours: 0,
    overtimeHours: 0,
    status: "absent",
    shift: "General",
    source: "manual",
    note: "No check-in recorded",
  },
  {
    id: "a5",
    employeeId: "e2",
    employeeName: "Meera Iyer",
    date: "2026-08-17",
    checkIn: "09:21",
    checkOut: "18:33",
    workedHours: 8.7,
    overtimeHours: 0,
    status: "present",
    shift: "General",
    source: "biometric",
  },
  {
    id: "a6",
    employeeId: "e7",
    employeeName: "Priyanka Rao",
    date: "2026-08-17",
    checkIn: null,
    checkOut: null,
    workedHours: 0,
    overtimeHours: 0,
    status: "leave",
    shift: "General",
    source: "manual",
    note: "Approved earned leave",
  },
  {
    id: "a7",
    employeeId: "e8",
    employeeName: "Karthik Nair",
    date: "2026-08-17",
    checkIn: "09:30",
    checkOut: "20:12",
    workedHours: 9.8,
    overtimeHours: 1.8,
    status: "present",
    shift: "General",
    source: "biometric",
  },
  {
    id: "a8",
    employeeId: "e4",
    employeeName: "Neha Kapoor",
    date: "2026-08-17",
    checkIn: "09:12",
    checkOut: "18:50",
    workedHours: 9.1,
    overtimeHours: 0.5,
    status: "present",
    shift: "General",
    source: "web",
  },
];

export const attendanceCorrections: AttendanceCorrection[] = [
  {
    id: "ac1",
    employeeName: "Sana Khan",
    date: "2026-08-14",
    requested: "Check-out 18:30 (missed punch)",
    reason: "Laptop battery died before punch-out",
    status: "pending",
  },
  {
    id: "ac2",
    employeeName: "Rohit Verma",
    date: "2026-08-11",
    requested: "Mark as WFH",
    reason: "Approved remote day, marked absent by device",
    status: "approved",
  },
  {
    id: "ac3",
    employeeName: "Daniel Fernandes",
    date: "2026-08-08",
    requested: "Check-in 09:20",
    reason: "Client visit, punched from field",
    status: "rejected",
  },
];

export const shifts: Shift[] = [
  {
    id: "s1",
    name: "General",
    start: "09:30",
    end: "18:30",
    breakMinutes: 60,
    graceMinutes: 15,
    weekOffs: ["Sat", "Sun"],
    assigned: 128,
    isNightShift: false,
  },
  {
    id: "s2",
    name: "Flexible",
    start: "11:00",
    end: "20:00",
    breakMinutes: 45,
    graceMinutes: 30,
    weekOffs: ["Sat", "Sun"],
    assigned: 26,
    isNightShift: false,
  },
  {
    id: "s3",
    name: "Support - Early",
    start: "06:30",
    end: "15:00",
    breakMinutes: 45,
    graceMinutes: 10,
    weekOffs: ["Sun", "Mon"],
    assigned: 14,
    isNightShift: false,
  },
  {
    id: "s4",
    name: "Support - Night",
    start: "22:00",
    end: "06:30",
    breakMinutes: 60,
    graceMinutes: 10,
    weekOffs: ["Wed", "Thu"],
    assigned: 9,
    isNightShift: true,
  },
];

export const leaveRequests: LeaveRequest[] = [
  {
    id: "l1",
    employeeId: "e3",
    employeeName: "Rohit Verma",
    type: "Casual",
    from: "2026-08-24",
    to: "2026-08-25",
    days: 2,
    reason: "Family function",
    status: "pending",
    appliedOn: "2026-08-15",
    approver: "Aarav Sharma",
  },
  {
    id: "l2",
    employeeId: "e5",
    employeeName: "Sana Khan",
    type: "Sick",
    from: "2026-08-18",
    to: "2026-08-18",
    days: 1,
    reason: "Fever",
    status: "pending",
    appliedOn: "2026-08-17",
    approver: "Aarav Sharma",
  },
  {
    id: "l3",
    employeeId: "e7",
    employeeName: "Priyanka Rao",
    type: "Earned",
    from: "2026-08-17",
    to: "2026-08-21",
    days: 5,
    reason: "Annual vacation",
    status: "approved",
    appliedOn: "2026-07-30",
    approver: "Neha Kapoor",
  },
  {
    id: "l4",
    employeeId: "e6",
    employeeName: "Daniel Fernandes",
    type: "Unpaid",
    from: "2026-08-05",
    to: "2026-08-06",
    days: 2,
    reason: "Personal",
    status: "rejected",
    appliedOn: "2026-08-01",
    approver: "Priyanka Rao",
  },
  {
    id: "l5",
    employeeId: "e8",
    employeeName: "Karthik Nair",
    type: "Comp-off",
    from: "2026-08-28",
    to: "2026-08-28",
    days: 1,
    reason: "Worked on payroll weekend",
    status: "pending",
    appliedOn: "2026-08-16",
    approver: "Neha Kapoor",
  },
];

export const payrollRuns: PayrollRun[] = [
  {
    id: "p1",
    period: "August 2026",
    employees: 177,
    gross: 41250000,
    deductions: 6820000,
    net: 34430000,
    status: "processed",
    payDate: "2026-08-31",
  },
  {
    id: "p2",
    period: "July 2026",
    employees: 174,
    gross: 40510000,
    deductions: 6710000,
    net: 33800000,
    status: "approved",
    payDate: "2026-07-31",
  },
  {
    id: "p3",
    period: "June 2026",
    employees: 171,
    gross: 39880000,
    deductions: 6605000,
    net: 33275000,
    status: "approved",
    payDate: "2026-06-30",
  },
];

export const payslips: Payslip[] = [
  {
    id: "ps1",
    employeeId: "e3",
    employeeName: "Rohit Verma",
    period: "July 2026",
    basic: 91000,
    hra: 36400,
    allowances: 24000,
    bonus: 0,
    pf: 10920,
    tax: 18400,
    otherDeductions: 1200,
    net: 120880,
    status: "paid",
  },
  {
    id: "ps2",
    employeeId: "e3",
    employeeName: "Rohit Verma",
    period: "June 2026",
    basic: 91000,
    hra: 36400,
    allowances: 24000,
    bonus: 25000,
    pf: 10920,
    tax: 21100,
    otherDeductions: 1200,
    net: 143180,
    status: "paid",
  },
  {
    id: "ps3",
    employeeId: "e5",
    employeeName: "Sana Khan",
    period: "July 2026",
    basic: 62500,
    hra: 25000,
    allowances: 15000,
    bonus: 0,
    pf: 7500,
    tax: 9100,
    otherDeductions: 900,
    net: 85000,
    status: "paid",
  },
  {
    id: "ps4",
    employeeId: "e8",
    employeeName: "Karthik Nair",
    period: "July 2026",
    basic: 58000,
    hra: 23200,
    allowances: 14000,
    bonus: 5000,
    pf: 6960,
    tax: 7800,
    otherDeductions: 600,
    net: 84840,
    status: "pending",
  },
];

export const assets: Asset[] = [
  {
    id: "as1",
    tag: "PF-LT-0091",
    name: 'MacBook Pro 14" M3',
    category: "Laptop",
    serial: "C02XY1ZZQ6L4",
    status: "assigned",
    condition: "good",
    assignedTo: "Rohit Verma",
    assignedOn: "2024-02-01",
    purchaseDate: "2024-01-18",
    value: 215000,
    warrantyTill: "2027-01-18",
    location: "Remote - Jaipur",
  },
  {
    id: "as2",
    tag: "PF-MN-0042",
    name: 'Dell UltraSharp 27"',
    category: "Monitor",
    serial: "DLU27-889120",
    status: "assigned",
    condition: "good",
    assignedTo: "Aarav Sharma",
    assignedOn: "2023-05-11",
    purchaseDate: "2023-04-28",
    value: 38000,
    warrantyTill: "2026-04-28",
    location: "Bengaluru HQ",
  },
  {
    id: "as3",
    tag: "PF-MB-0017",
    name: "iPhone 14",
    category: "Mobile",
    serial: "IP14-556677",
    status: "in-repair",
    condition: "damaged",
    assignedTo: "Daniel Fernandes",
    assignedOn: "2023-12-04",
    purchaseDate: "2023-11-20",
    value: 72000,
    warrantyTill: "2025-11-20",
    location: "Mumbai Office",
  },
  {
    id: "as4",
    tag: "PF-KB-0210",
    name: "Keychron K3 Pro",
    category: "Keyboard",
    serial: "KC3-771201",
    status: "available",
    condition: "new",
    assignedTo: null,
    assignedOn: null,
    purchaseDate: "2026-06-12",
    value: 9500,
    warrantyTill: "2028-06-12",
    location: "Bengaluru Store",
  },
  {
    id: "as5",
    tag: "PF-MS-0188",
    name: "Logitech MX Master 3S",
    category: "Mouse",
    serial: "LG3S-441122",
    status: "assigned",
    condition: "fair",
    assignedTo: "Sana Khan",
    assignedOn: "2024-01-15",
    purchaseDate: "2023-12-30",
    value: 8900,
    warrantyTill: "2025-12-30",
    location: "Hyderabad Office",
  },
  {
    id: "as6",
    tag: "PF-ID-1005",
    name: "Access ID Card",
    category: "ID Card",
    serial: "IDC-1005",
    status: "assigned",
    condition: "good",
    assignedTo: "Sana Khan",
    assignedOn: "2024-01-08",
    purchaseDate: "2024-01-08",
    value: 500,
    warrantyTill: "2027-01-08",
    location: "Hyderabad Office",
  },
  {
    id: "as7",
    tag: "PF-DT-0006",
    name: "HP EliteDesk 800",
    category: "Desktop",
    serial: "HPE800-2211",
    status: "retired",
    condition: "damaged",
    assignedTo: null,
    assignedOn: null,
    purchaseDate: "2019-07-19",
    value: 65000,
    warrantyTill: "2022-07-19",
    location: "Bengaluru Store",
  },
  {
    id: "as8",
    tag: "PF-OT-0033",
    name: "Standing Desk Converter",
    category: "Other",
    serial: "SDC-9082",
    status: "available",
    condition: "good",
    assignedTo: null,
    assignedOn: null,
    purchaseDate: "2025-03-04",
    value: 21000,
    warrantyTill: "2028-03-04",
    location: "Pune Office",
  },
];

export const assetEvents: AssetEvent[] = [
  {
    id: "ae1",
    assetTag: "PF-MB-0017",
    type: "repair",
    actor: "IT Helpdesk",
    date: "2026-08-12",
    note: "Screen replacement sent to authorised service centre",
  },
  {
    id: "ae2",
    assetTag: "PF-LT-0091",
    type: "assigned",
    actor: "Meera Iyer",
    date: "2024-02-01",
    note: "Issued to Rohit Verma on joining",
  },
  {
    id: "ae3",
    assetTag: "PF-DT-0006",
    type: "returned",
    actor: "IT Helpdesk",
    date: "2025-11-02",
    note: "Returned during hardware refresh cycle",
  },
  {
    id: "ae4",
    assetTag: "PF-MS-0188",
    type: "audit",
    actor: "Asset Audit Bot",
    date: "2026-07-01",
    note: "Quarterly audit - condition marked fair",
  },
  {
    id: "ae5",
    assetTag: "PF-MN-0042",
    type: "replaced",
    actor: "IT Helpdesk",
    date: "2026-05-18",
    note: "HDMI cable replaced",
  },
];

export const jobOpenings: JobOpening[] = [
  {
    id: "j1",
    title: "Senior Backend Engineer",
    department: "Engineering",
    location: "Bengaluru / Remote",
    type: "full-time",
    openings: 3,
    applicants: 148,
    stage: "open",
    postedOn: "2026-07-22",
    hiringManager: "Aarav Sharma",
  },
  {
    id: "j2",
    title: "Product Designer II",
    department: "Design",
    location: "Hyderabad",
    type: "full-time",
    openings: 1,
    applicants: 64,
    stage: "open",
    postedOn: "2026-08-02",
    hiringManager: "Sana Khan",
  },
  {
    id: "j3",
    title: "Enterprise Account Executive",
    department: "Sales",
    location: "Mumbai",
    type: "full-time",
    openings: 2,
    applicants: 91,
    stage: "on-hold",
    postedOn: "2026-06-15",
    hiringManager: "Priyanka Rao",
  },
  {
    id: "j4",
    title: "HR Intern",
    department: "Human Resources",
    location: "Pune",
    type: "intern",
    openings: 2,
    applicants: 210,
    stage: "closed",
    postedOn: "2026-04-09",
    hiringManager: "Meera Iyer",
  },
];

export const candidates: Candidate[] = [
  {
    id: "c1",
    name: "Ishaan Gupta",
    role: "Senior Backend Engineer",
    stage: "interview",
    experience: "7 yrs",
    source: "Referral",
    rating: 4.5,
    appliedOn: "2026-08-01",
  },
  {
    id: "c2",
    name: "Fatima Sheikh",
    role: "Product Designer II",
    stage: "offer",
    experience: "5 yrs",
    source: "LinkedIn",
    rating: 4.8,
    appliedOn: "2026-07-19",
  },
  {
    id: "c3",
    name: "Arjun Menon",
    role: "Senior Backend Engineer",
    stage: "screening",
    experience: "6 yrs",
    source: "Careers Page",
    rating: 3.9,
    appliedOn: "2026-08-11",
  },
  {
    id: "c4",
    name: "Lily Thomas",
    role: "Enterprise Account Executive",
    stage: "applied",
    experience: "9 yrs",
    source: "Agency",
    rating: 4.1,
    appliedOn: "2026-08-14",
  },
  {
    id: "c5",
    name: "Vikas Yadav",
    role: "Product Designer II",
    stage: "rejected",
    experience: "3 yrs",
    source: "LinkedIn",
    rating: 2.8,
    appliedOn: "2026-07-28",
  },
  {
    id: "c6",
    name: "Nadia Rahman",
    role: "Senior Backend Engineer",
    stage: "hired",
    experience: "8 yrs",
    source: "Referral",
    rating: 4.9,
    appliedOn: "2026-06-30",
  },
];

export const onboardingJourneys: OnboardingJourney[] = [
  {
    id: "o1",
    employeeName: "Nadia Rahman",
    designation: "Senior Backend Engineer",
    startDate: "2026-09-01",
    buddy: "Rohit Verma",
    progress: 62,
    tasks: [
      { id: "o1t1", label: "Offer accepted", owner: "Talent", done: true },
      { id: "o1t2", label: "Background verification", owner: "HR Ops", done: true },
      { id: "o1t3", label: "Laptop allocation", owner: "IT", done: true },
      { id: "o1t4", label: "Payroll setup", owner: "Finance", done: false },
      { id: "o1t5", label: "Day-1 orientation", owner: "HR", done: false },
    ],
  },
  {
    id: "o2",
    employeeName: "Fatima Sheikh",
    designation: "Product Designer II",
    startDate: "2026-09-15",
    buddy: "Sana Khan",
    progress: 25,
    tasks: [
      { id: "o2t1", label: "Offer accepted", owner: "Talent", done: true },
      { id: "o2t2", label: "Document collection", owner: "HR Ops", done: false },
      { id: "o2t3", label: "Asset request raised", owner: "IT", done: false },
      { id: "o2t4", label: "Team intro scheduled", owner: "Manager", done: false },
    ],
  },
];

export const goals: Goal[] = [
  {
    id: "g1",
    employeeName: "Rohit Verma",
    title: "Ship design-system v2 across web app",
    category: "Business",
    progress: 72,
    weight: 30,
    dueDate: "2026-09-30",
    status: "on-track",
  },
  {
    id: "g2",
    employeeName: "Rohit Verma",
    title: "Reduce page LCP below 2.0s",
    category: "Quality",
    progress: 45,
    weight: 25,
    dueDate: "2026-10-15",
    status: "at-risk",
  },
  {
    id: "g3",
    employeeName: "Sana Khan",
    title: "Complete accessibility certification",
    category: "Learning",
    progress: 90,
    weight: 20,
    dueDate: "2026-08-31",
    status: "on-track",
  },
  {
    id: "g4",
    employeeName: "Daniel Fernandes",
    title: "Close 12 enterprise deals in Q3",
    category: "Business",
    progress: 30,
    weight: 40,
    dueDate: "2026-09-30",
    status: "delayed",
  },
  {
    id: "g5",
    employeeName: "Karthik Nair",
    title: "Automate payroll reconciliation",
    category: "Quality",
    progress: 100,
    weight: 25,
    dueDate: "2026-07-31",
    status: "completed",
  },
];

export const performanceReviews: PerformanceReview[] = [
  {
    id: "pr1",
    employeeName: "Rohit Verma",
    cycle: "H1 2026",
    reviewer: "Aarav Sharma",
    selfScore: 4.2,
    managerScore: 4.0,
    finalRating: 4.1,
    status: "closed",
  },
  {
    id: "pr2",
    employeeName: "Sana Khan",
    cycle: "H1 2026",
    reviewer: "Aarav Sharma",
    selfScore: 3.8,
    managerScore: 4.1,
    finalRating: 4.0,
    status: "submitted",
  },
  {
    id: "pr3",
    employeeName: "Daniel Fernandes",
    cycle: "H1 2026",
    reviewer: "Priyanka Rao",
    selfScore: 3.4,
    managerScore: 3.0,
    finalRating: 3.2,
    status: "in-progress",
  },
  {
    id: "pr4",
    employeeName: "Karthik Nair",
    cycle: "H1 2026",
    reviewer: "Neha Kapoor",
    selfScore: 0,
    managerScore: 0,
    finalRating: 0,
    status: "not-started",
  },
];

export const documents: DocumentItem[] = [
  {
    id: "doc1",
    name: "Offer Letter - Rohit Verma.pdf",
    category: "Contract",
    owner: "Rohit Verma",
    size: "412 KB",
    uploadedOn: "2023-02-10",
    expiresOn: null,
    verified: true,
  },
  {
    id: "doc2",
    name: "Aadhaar Card.pdf",
    category: "Identity",
    owner: "Sana Khan",
    size: "298 KB",
    uploadedOn: "2024-01-05",
    expiresOn: null,
    verified: true,
  },
  {
    id: "doc3",
    name: "Degree Certificate.pdf",
    category: "Education",
    owner: "Karthik Nair",
    size: "1.1 MB",
    uploadedOn: "2023-09-02",
    expiresOn: null,
    verified: false,
  },
  {
    id: "doc4",
    name: "Work Permit.pdf",
    category: "Identity",
    owner: "Daniel Fernandes",
    size: "660 KB",
    uploadedOn: "2022-11-01",
    expiresOn: "2026-10-31",
    verified: true,
  },
  {
    id: "doc5",
    name: "Leave Policy 2026.pdf",
    category: "Policy",
    owner: "Company Wide",
    size: "220 KB",
    uploadedOn: "2026-01-04",
    expiresOn: null,
    verified: true,
  },
  {
    id: "doc6",
    name: "Form 16 - FY2025-26.pdf",
    category: "Payroll",
    owner: "Rohit Verma",
    size: "180 KB",
    uploadedOn: "2026-06-14",
    expiresOn: null,
    verified: true,
  },
];

export const expenses: ExpenseClaim[] = [
  {
    id: "ex1",
    employeeName: "Daniel Fernandes",
    category: "Travel",
    amount: 18400,
    date: "2026-08-09",
    status: "pending",
    note: "Client visit - Pune",
  },
  {
    id: "ex2",
    employeeName: "Rohit Verma",
    category: "Internet",
    amount: 1499,
    date: "2026-08-01",
    status: "approved",
    note: "Monthly broadband reimbursement",
  },
  {
    id: "ex3",
    employeeName: "Sana Khan",
    category: "Equipment",
    amount: 7200,
    date: "2026-07-24",
    status: "reimbursed",
    note: "Drawing tablet stylus",
  },
  {
    id: "ex4",
    employeeName: "Priyanka Rao",
    category: "Client",
    amount: 26500,
    date: "2026-07-18",
    status: "rejected",
    note: "Missing itemised invoice",
  },
];

export const tickets: HelpdeskTicket[] = [
  {
    id: "t1",
    subject: "Payslip shows incorrect PF deduction",
    category: "Payroll",
    raisedBy: "Karthik Nair",
    priority: "high",
    status: "in-progress",
    createdOn: "2026-08-14",
    assignee: "Finance Ops",
  },
  {
    id: "t2",
    subject: "Need VPN access for remote work",
    category: "IT",
    raisedBy: "Rohit Verma",
    priority: "medium",
    status: "open",
    createdOn: "2026-08-16",
    assignee: "IT Helpdesk",
  },
  {
    id: "t3",
    subject: "Attendance marked absent on approved WFH",
    category: "Attendance",
    raisedBy: "Sana Khan",
    priority: "urgent",
    status: "open",
    createdOn: "2026-08-17",
    assignee: "HR Ops",
  },
  {
    id: "t4",
    subject: "Clarification on relocation policy",
    category: "Policy",
    raisedBy: "Daniel Fernandes",
    priority: "low",
    status: "resolved",
    createdOn: "2026-08-02",
    assignee: "Meera Iyer",
  },
];

export const announcements: Announcement[] = [
  {
    id: "an1",
    title: "Independence Day holiday & long weekend",
    body: "Offices remain closed on 15 August. Support shifts follow the rotational roster shared by your manager.",
    audience: "Everyone",
    author: "Meera Iyer",
    publishedOn: "2026-08-11",
    pinned: true,
    priority: "urgent",
    isActive: true,
    expired: false,
    read: false,
    expiresAt: null,
    targetScope: "organization",
    targetDepartmentId: null,
    targetDepartmentName: null,
    targetRole: null,
  },
  {
    id: "an2",
    title: "H2 performance cycle opens 1 September",
    body: "Self-assessments must be submitted by 12 September. Managers get two weeks for calibration.",
    audience: "Everyone",
    author: "Neha Kapoor",
    publishedOn: "2026-08-13",
    pinned: true,
    priority: "urgent",
    isActive: true,
    expired: false,
    read: true,
    expiresAt: null,
    targetScope: "organization",
    targetDepartmentId: null,
    targetDepartmentName: null,
    targetRole: null,
  },
  {
    id: "an3",
    title: "New laptop refresh policy for engineering",
    body: "Devices older than 3 years are eligible for replacement. Raise an asset request from the Assets module.",
    audience: "Everyone",
    author: "IT Helpdesk",
    publishedOn: "2026-08-06",
    pinned: false,
    priority: "normal",
    isActive: true,
    expired: false,
    read: false,
    expiresAt: null,
    targetScope: "organization",
    targetDepartmentId: null,
    targetDepartmentName: null,
    targetRole: null,
  },
];

export const notifications: NotificationItem[] = [
  {
    id: "n1",
    title: "Leave request awaiting your approval",
    description: "Sana Khan applied for 1 day sick leave on 18 Aug.",
    type: "leave",
    createdAt: "12 min ago",
    read: false,
  },
  {
    id: "n2",
    title: "August payroll moved to processing",
    description: "177 employees included. Locks on 28 Aug.",
    type: "payroll",
    createdAt: "2 hours ago",
    read: false,
  },
  {
    id: "n3",
    title: "Asset repair update",
    description: "iPhone 14 (PF-MB-0017) is at the service centre.",
    type: "asset",
    createdAt: "Yesterday",
    read: true,
  },
  {
    id: "n4",
    title: "3 attendance corrections pending",
    description: "Review missed punches for the week of 10 Aug.",
    type: "attendance",
    createdAt: "2 days ago",
    read: true,
  },
];

export const auditEntries: AuditEntry[] = [
  {
    id: "au1",
    actor: "Neha Kapoor",
    action: "Updated payroll run status to Processing",
    entity: "Payroll / August 2026",
    ip: "10.4.22.18",
    timestamp: "2026-08-17 14:02",
  },
  {
    id: "au2",
    actor: "Meera Iyer",
    action: "Approved attendance correction",
    entity: "Attendance / Rohit Verma",
    ip: "10.4.19.7",
    timestamp: "2026-08-17 11:47",
  },
  {
    id: "au3",
    actor: "System",
    action: "Failed login attempts threshold reached",
    entity: "Auth / daniel.f@jeevijay-hrms.example",
    ip: "103.21.44.9",
    timestamp: "2026-08-16 22:10",
  },
  {
    id: "au4",
    actor: "IT Helpdesk",
    action: "Marked asset in-repair",
    entity: "Asset / PF-MB-0017",
    ip: "10.4.30.2",
    timestamp: "2026-08-12 09:33",
  },
];

export const attendanceTrend: TrendPoint[] = [
  { label: "Mon", present: 142, absent: 9, wfh: 26 },
  { label: "Tue", present: 148, absent: 6, wfh: 23 },
  { label: "Wed", present: 139, absent: 11, wfh: 27 },
  { label: "Thu", present: 151, absent: 5, wfh: 21 },
  { label: "Fri", present: 133, absent: 8, wfh: 36 },
  { label: "Sat", present: 41, absent: 2, wfh: 12 },
];

export const headcountTrend: HeadcountPoint[] = [
  { label: "Mar", joined: 9, exited: 4, headcount: 160 },
  { label: "Apr", joined: 7, exited: 3, headcount: 164 },
  { label: "May", joined: 11, exited: 5, headcount: 170 },
  { label: "Jun", joined: 6, exited: 5, headcount: 171 },
  { label: "Jul", joined: 8, exited: 5, headcount: 174 },
  { label: "Aug", joined: 6, exited: 3, headcount: 177 },
];
