-- Kinetix HRMS schema. Execute in Supabase SQL Editor or with `supabase db push`.
create extension if not exists pgcrypto;

create table if not exists public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, logo_url text, timezone text not null default 'UTC', currency text not null default 'USD', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.roles (id uuid primary key default gen_random_uuid(), name text not null unique check (lower(name) in ('admin','hr','manager','employee')), description text, created_at timestamptz not null default now());
create table if not exists public.permissions (id uuid primary key default gen_random_uuid(), key text not null unique, description text, created_at timestamptz not null default now());
create table if not exists public.role_permissions (role_id uuid not null references public.roles(id) on delete cascade, permission_id uuid not null references public.permissions(id) on delete cascade, primary key(role_id, permission_id));
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, organization_id uuid references public.organizations(id) on delete set null, role_id uuid references public.roles(id) on delete set null, full_name text not null default '', email text not null default '', avatar_url text, designation text, department text, phone text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.departments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, code text, head_id uuid references public.profiles(id) on delete set null, cost_center text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,name));
create table if not exists public.designations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, department_id uuid references public.departments(id) on delete set null, name text not null, level text, description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,name));
create table if not exists public.shifts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, start_time time not null, end_time time not null, break_minutes int not null default 0 check(break_minutes>=0), grace_minutes int not null default 0 check(grace_minutes>=0), week_offs text[] not null default '{}', is_night_shift boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,name));
create table if not exists public.employees (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, user_id uuid unique references public.profiles(id) on delete set null, employee_code text not null, first_name text not null, last_name text not null, email text not null, phone text, avatar_url text, department_id uuid references public.departments(id) on delete set null, designation_id uuid references public.designations(id) on delete set null, manager_id uuid references public.employees(id) on delete set null, role text not null default 'employee' check(role in ('admin','hr','manager','employee')), location text, joined_on date, status text not null default 'active' check(status in ('active','probation','notice','resigned','on-leave')), employment_type text not null default 'full-time' check(employment_type in ('full-time','part-time','contract','intern')), shift_id uuid references public.shifts(id) on delete set null, gender text, date_of_birth date, blood_group text, marital_status text, address text, emergency_contact jsonb not null default '{}', bank_details jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,employee_code), unique(organization_id,email));
create table if not exists public.shift_assignments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, shift_id uuid not null references public.shifts(id) on delete cascade, employee_id uuid not null references public.employees(id) on delete cascade, effective_from date not null, effective_to date, created_at timestamptz not null default now(), unique(employee_id,effective_from));
create table if not exists public.attendance (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id uuid not null references public.employees(id) on delete cascade, attendance_date date not null, check_in timestamptz, check_out timestamptz, worked_hours numeric(6,2) not null default 0, overtime_hours numeric(6,2) not null default 0, status text not null default 'present' check(status in ('present','absent','late','half-day','wfh','leave','holiday','week-off')), shift_id uuid references public.shifts(id) on delete set null, source text not null default 'web' check(source in ('web','mobile','biometric','manual')), note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(employee_id,attendance_date));
create table if not exists public.attendance_corrections (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id uuid not null references public.employees(id) on delete cascade, attendance_id uuid references public.attendance(id) on delete set null, attendance_date date not null, requested text not null, reason text not null, status text not null default 'pending' check(status in ('pending','approved','rejected','cancelled')), reviewed_by uuid references public.profiles(id) on delete set null, reviewed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.leave_types (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, annual_days numeric(6,2) not null default 0, is_paid boolean not null default true, created_at timestamptz not null default now(), unique(organization_id,name));
create table if not exists public.leave_balances (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id uuid not null references public.employees(id) on delete cascade, leave_type_id uuid not null references public.leave_types(id) on delete cascade, year int not null, allocated numeric(6,2) not null default 0, used numeric(6,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(employee_id,leave_type_id,year));
create table if not exists public.leave (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id uuid not null references public.employees(id) on delete cascade, leave_type_id uuid references public.leave_types(id) on delete set null, leave_type text not null, from_date date not null, to_date date not null, days numeric(6,2) not null check(days>0), reason text not null, status text not null default 'pending' check(status in ('pending','approved','rejected','cancelled')), approver_id uuid references public.profiles(id) on delete set null, applied_on timestamptz not null default now(), decided_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(to_date>=from_date));
create table if not exists public.salary_structures (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id uuid not null references public.employees(id) on delete cascade, effective_from date not null, basic numeric(14,2) not null default 0, hra numeric(14,2) not null default 0, allowances numeric(14,2) not null default 0, deductions numeric(14,2) not null default 0, ctc_annual numeric(14,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.payroll_runs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, period text not null, employee_count int not null default 0, gross numeric(14,2) not null default 0, deductions numeric(14,2) not null default 0, net numeric(14,2) not null default 0, status text not null default 'draft' check(status in ('draft','processing','paid','on-hold')), pay_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,period));
create table if not exists public.payslips (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, payroll_run_id uuid references public.payroll_runs(id) on delete set null, employee_id uuid not null references public.employees(id) on delete cascade, period text not null, basic numeric(14,2) not null default 0, hra numeric(14,2) not null default 0, allowances numeric(14,2) not null default 0, bonus numeric(14,2) not null default 0, pf numeric(14,2) not null default 0, tax numeric(14,2) not null default 0, other_deductions numeric(14,2) not null default 0, net numeric(14,2) not null default 0, status text not null default 'pending' check(status in ('paid','pending')), payslip_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(employee_id,period));
create table if not exists public.assets (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, tag text not null, name text not null, category text not null, serial text, status text not null default 'available' check(status in ('assigned','available','in-repair','retired','lost')), condition text not null default 'new' check(condition in ('new','good','fair','damaged')), assigned_to uuid references public.employees(id) on delete set null, assigned_on date, purchase_date date, value numeric(14,2) not null default 0, warranty_till date, location text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,tag));
create table if not exists public.asset_history (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, asset_id uuid not null references public.assets(id) on delete cascade, event_type text not null check(event_type in ('assigned','returned','repair','replaced','audit')), actor_id uuid references public.profiles(id) on delete set null, note text, created_at timestamptz not null default now());
create table if not exists public.jobs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, title text not null, department_id uuid references public.departments(id) on delete set null, location text, employment_type text not null default 'full-time' check(employment_type in ('full-time','part-time','contract','intern')), openings int not null default 1, applicants int not null default 0, stage text not null default 'draft' check(stage in ('draft','open','on-hold','closed')), posted_on date, hiring_manager_id uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.candidates (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, job_id uuid references public.jobs(id) on delete set null, name text not null, email text, phone text, role text not null, stage text not null default 'applied' check(stage in ('applied','screening','interview','offer','hired','rejected')), experience text, source text, rating numeric(3,1) check(rating between 0 and 5), applied_on date not null default current_date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.interviews (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, candidate_id uuid not null references public.candidates(id) on delete cascade, interviewer_id uuid references public.profiles(id) on delete set null, scheduled_at timestamptz, status text not null default 'scheduled' check(status in ('scheduled','completed','cancelled')), feedback text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.offers (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, candidate_id uuid not null references public.candidates(id) on delete cascade, offered_ctc numeric(14,2) not null default 0, joining_date date, status text not null default 'draft' check(status in ('draft','sent','accepted','declined','expired')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.onboarding (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id uuid references public.employees(id) on delete cascade, candidate_id uuid references public.candidates(id) on delete set null, start_date date not null, buddy_id uuid references public.profiles(id) on delete set null, status text not null default 'not-started' check(status in ('not-started','in-progress','completed','on-hold')), progress int not null default 0 check(progress between 0 and 100), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.onboarding_tasks (id uuid primary key default gen_random_uuid(), onboarding_id uuid not null references public.onboarding(id) on delete cascade, label text not null, owner_id uuid references public.profiles(id) on delete set null, is_done boolean not null default false, due_date date, completed_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.goals (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id uuid not null references public.employees(id) on delete cascade, title text not null, category text not null default 'Business' check(category in ('Business','Learning','Team','Quality')), progress int not null default 0 check(progress between 0 and 100), weight numeric(6,2) not null default 0, due_date date, status text not null default 'on-track' check(status in ('on-track','at-risk','delayed','completed')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.performance_reviews (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id uuid not null references public.employees(id) on delete cascade, cycle text not null, reviewer_id uuid references public.profiles(id) on delete set null, self_score numeric(4,2), manager_score numeric(4,2), final_rating numeric(4,2), status text not null default 'not-started' check(status in ('not-started','in-progress','submitted','closed')), review_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.documents (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id uuid references public.employees(id) on delete cascade, name text not null, category text not null default 'Other' check(category in ('Identity','Education','Contract','Policy','Payroll','Other')), storage_path text, size_bytes bigint not null default 0, uploaded_by uuid references public.profiles(id) on delete set null, uploaded_on date not null default current_date, expires_on date, verified boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.expenses (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id uuid not null references public.employees(id) on delete cascade, category text not null default 'Other' check(category in ('Travel','Food','Internet','Equipment','Client','Other')), amount numeric(14,2) not null check(amount>=0), expense_date date not null default current_date, status text not null default 'pending' check(status in ('pending','approved','rejected','cancelled','reimbursed')), note text, reviewed_by uuid references public.profiles(id) on delete set null, reimbursed_on date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.helpdesk_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, raised_by uuid not null references public.profiles(id) on delete cascade, subject text not null, category text not null default 'Other' check(category in ('Payroll','IT','Attendance','Policy','Facilities','Other')), priority text not null default 'medium' check(priority in ('low','medium','high','urgent')), status text not null default 'open' check(status in ('open','in-progress','resolved','closed')), assignee_id uuid references public.profiles(id) on delete set null, description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.announcements (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, title text not null, body text not null, audience text not null default 'All' check(audience in ('All','Engineering','Sales','Managers')), author_id uuid references public.profiles(id) on delete set null, published_on timestamptz not null default now(), pinned boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.announcement_reads (announcement_id uuid not null references public.announcements(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, read_at timestamptz not null default now(), primary key(announcement_id,user_id));
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, title text not null, description text not null default '', type text not null default 'system' check(type in ('leave','payroll','asset','attendance','system')), read boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.audit_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, actor_id uuid references public.profiles(id) on delete set null, action text not null, entity text not null, entity_id uuid, ip inet, severity text not null default 'info' check(severity in ('info','warning','critical')), metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists public.organization_settings (organization_id uuid primary key references public.organizations(id) on delete cascade, settings jsonb not null default '{}', updated_by uuid references public.profiles(id) on delete set null, updated_at timestamptz not null default now());
create table if not exists public.user_preferences (user_id uuid primary key references public.profiles(id) on delete cascade, theme text not null default 'light' check(theme in ('light','dark')), preferences jsonb not null default '{}', updated_at timestamptz not null default now());

create or replace function public.set_updated_at() returns trigger language plpgsql security invoker set search_path=public as $$ begin new.updated_at=now(); return new; end; $$;
do $$ declare t text; begin foreach t in array array['organizations','profiles','departments','designations','shifts','employees','shift_assignments','attendance','attendance_corrections','leave_balances','leave','salary_structures','payroll_runs','payslips','assets','jobs','candidates','interviews','offers','onboarding','goals','performance_reviews','documents','expenses','helpdesk_requests','announcements','organization_settings','user_preferences'] loop execute format('drop trigger if exists set_updated_at on public.%I',t); execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()',t); end loop; end $$;
create or replace function public.current_org_id() returns uuid language sql stable security definer set search_path=public as $$ select organization_id from public.profiles where id=auth.uid() and is_active=true; $$;
create or replace function public.current_role() returns text language sql stable security definer set search_path=public as $$ select lower(r.name) from public.profiles p join public.roles r on r.id=p.role_id where p.id=auth.uid() and p.is_active=true limit 1; $$;
create or replace function public.is_org_member(target_org uuid) returns boolean language sql stable security definer set search_path=public as $$ select target_org is not null and target_org=public.current_org_id(); $$;
create or replace function public.is_admin_or_hr() returns boolean language sql stable security definer set search_path=public as $$ select public.current_role() in ('admin','hr'); $$;

insert into public.roles(name,description) values ('admin','Full organization administration'),('hr','Human resources administration'),('manager','Team management'),('employee','Employee self-service') on conflict(name) do nothing;
create index if not exists idx_profiles_org on public.profiles(organization_id);
create index if not exists idx_employees_org on public.employees(organization_id);
create index if not exists idx_employees_manager on public.employees(manager_id);
create index if not exists idx_attendance_employee_date on public.attendance(employee_id,attendance_date desc);
create index if not exists idx_leave_employee_status on public.leave(employee_id,status);
create index if not exists idx_payslips_employee_period on public.payslips(employee_id,period desc);
create index if not exists idx_assets_assignee on public.assets(assigned_to);
create index if not exists idx_candidates_job_stage on public.candidates(job_id,stage);
create index if not exists idx_goals_employee_status on public.goals(employee_id,status);
create index if not exists idx_documents_employee on public.documents(employee_id);
create index if not exists idx_expenses_employee_status on public.expenses(employee_id,status);
create index if not exists idx_helpdesk_raised_status on public.helpdesk_requests(raised_by,status);
create index if not exists idx_notifications_user_created on public.notifications(user_id,created_at desc);
create index if not exists idx_audit_org_created on public.audit_logs(organization_id,created_at desc);

do $$ declare t text; begin foreach t in array array['organizations','roles','permissions','role_permissions','profiles','departments','designations','employees','shifts','shift_assignments','attendance','attendance_corrections','leave_types','leave_balances','leave','salary_structures','payroll_runs','payslips','assets','asset_history','jobs','candidates','interviews','offers','onboarding','onboarding_tasks','goals','performance_reviews','documents','expenses','helpdesk_requests','announcements','announcement_reads','notifications','audit_logs','organization_settings','user_preferences'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;

create policy organizations_member_select on public.organizations for select using (id=public.current_org_id());
create policy roles_authenticated_select on public.roles for select to authenticated using (true);
create policy permissions_authenticated_select on public.permissions for select to authenticated using (true);
create policy role_permissions_authenticated_select on public.role_permissions for select to authenticated using (true);
create policy profiles_member_select on public.profiles for select using (id=auth.uid() or organization_id=public.current_org_id());
create policy profiles_self_update on public.profiles for update using (id=auth.uid()) with check (id=auth.uid());
create policy user_preferences_self_all on public.user_preferences for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy announcement_reads_self_all on public.announcement_reads for all using (user_id=auth.uid()) with check (user_id=auth.uid());

do $$ declare t text; begin foreach t in array array['departments','designations','employees','shifts','shift_assignments','attendance','attendance_corrections','leave_types','leave_balances','leave','salary_structures','payroll_runs','payslips','assets','asset_history','jobs','candidates','interviews','offers','onboarding','onboarding_tasks','goals','performance_reviews','documents','expenses','helpdesk_requests','announcements','notifications','audit_logs','organization_settings'] loop execute format('create policy %I on public.%I for select using (public.is_org_member(organization_id))',t||'_select',t); execute format('create policy %I on public.%I for insert with check (public.is_org_member(organization_id))',t||'_insert',t); execute format('create policy %I on public.%I for update using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id))',t||'_update',t); execute format('create policy %I on public.%I for delete using (public.is_org_member(organization_id) and public.is_admin_or_hr())',t||'_delete',t); end loop; end $$;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ declare employee_role uuid; begin select id into employee_role from public.roles where name='employee'; insert into public.profiles(id,full_name,email,role_id) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.email,''),employee_role) on conflict(id) do update set email=excluded.email,updated_at=now(); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
